import {useEffect,useState} from "react";
import {salaryApi,employeeApi} from "../../services/api";
import PageHeader from "../../components/PageHeader";

export default function Salary(){
 const [rows,setRows]=useState([]),[employees,setEmployees]=useState([]),[form,setForm]=useState({employeeId:"",month:new Date().getMonth()+1,year:new Date().getFullYear(),workingDays:26,allowances:0,otherDeduction:0});
 const load=()=>{salaryApi.getAll().then(r=>setRows(r.data));employeeApi.getAll().then(r=>setEmployees(r.data));};useEffect(load,[]);
 const save=async e=>{e.preventDefault();await salaryApi.generate(form.employeeId,{month:form.month,year:form.year,workingDays:form.workingDays,allowances:form.allowances,otherDeduction:form.otherDeduction});load();};
 const set=(k,v)=>setForm({...form,[k]:v});
 return <><PageHeader title="Salary & Payroll" subtitle="Generate monthly salary based on attendance"/>
 <div className="form-panel mb-4"><form className="row g-3" onSubmit={save}><div className="col-md-4"><label>Employee</label><select className="form-select" required value={form.employeeId} onChange={e=>set("employeeId",e.target.value)}><option value="">Select</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employeeId} - {e.firstName} {e.lastName}</option>)}</select></div><div className="col-md-2"><label>Month</label><input className="form-control" type="number" min="1" max="12" value={form.month} onChange={e=>set("month",e.target.value)}/></div><div className="col-md-2"><label>Year</label><input className="form-control" type="number" value={form.year} onChange={e=>set("year",e.target.value)}/></div><div className="col-md-2"><label>Working Days</label><input className="form-control" type="number" value={form.workingDays} onChange={e=>set("workingDays",e.target.value)}/></div><div className="col-md-2"><label>Allowances</label><input className="form-control" type="number" value={form.allowances} onChange={e=>set("allowances",e.target.value)}/></div><div className="col-md-2"><label>Other Deduction</label><input className="form-control" type="number" value={form.otherDeduction} onChange={e=>set("otherDeduction",e.target.value)}/></div><div className="col-12"><button className="btn btn-primary">Generate Salary</button></div></form></div>
 <div className="table-card"><div className="table-responsive"><table className="table"><thead><tr><th>Employee</th><th>Month</th><th>Present</th><th>Absent</th><th>Half Day</th><th>Deduction</th><th>Net Salary</th></tr></thead><tbody>{rows.map(s=><tr key={s.id}><td>{s.employee?.employeeId}</td><td>{s.month}/{s.year}</td><td>{s.presentDays}</td><td>{s.absentDays}</td><td>{s.halfDays}</td><td>₹{Number(s.absentDeduction||0).toLocaleString("en-IN")}</td><td><strong>₹{Number(s.netSalary||0).toLocaleString("en-IN")}</strong></td></tr>)}</tbody></table></div></div></>;
}
