import {useEffect,useState} from "react";
import {taskApi,employeeApi} from "../../services/api";
import PageHeader from "../../components/PageHeader";

export default function Tasks(){
 const [rows,setRows]=useState([]),[employees,setEmployees]=useState([]),[form,setForm]=useState({employeeId:"",title:"",description:"",priority:"MEDIUM",dueDate:""});
 const load=()=>{taskApi.getAll().then(r=>setRows(r.data));employeeApi.getAll().then(r=>setEmployees(r.data));};useEffect(load,[]);
 const save=async e=>{e.preventDefault();await taskApi.add(form);setForm({employeeId:"",title:"",description:"",priority:"MEDIUM",dueDate:""});load();};
 const set=(k,v)=>setForm({...form,[k]:v});
 return <><PageHeader title="Tasks" subtitle="Assign and manage employee tasks"/>
 <div className="form-panel mb-4"><form className="row g-3" onSubmit={save}><div className="col-md-4"><label>Employee</label><select className="form-select" required value={form.employeeId} onChange={e=>set("employeeId",e.target.value)}><option value="">Select</option>{employees.map(e=><option key={e.id} value={e.id}>{e.employeeId} - {e.firstName}</option>)}</select></div><div className="col-md-4"><label>Title</label><input className="form-control" required value={form.title} onChange={e=>set("title",e.target.value)}/></div><div className="col-md-4"><label>Due Date</label><input className="form-control" type="date" value={form.dueDate} onChange={e=>set("dueDate",e.target.value)}/></div><div className="col-md-4"><label>Priority</label><select className="form-select" value={form.priority} onChange={e=>set("priority",e.target.value)}><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></div><div className="col-md-8"><label>Description</label><input className="form-control" value={form.description} onChange={e=>set("description",e.target.value)}/></div><div className="col-12"><button className="btn btn-primary">Assign Task</button></div></form></div>
 <div className="table-card"><div className="table-responsive"><table className="table"><thead><tr><th>Employee</th><th>Task</th><th>Priority</th><th>Due</th><th>Status</th><th></th></tr></thead><tbody>{rows.map(t=><tr key={t.id}><td>{t.employee?.employeeId}</td><td><strong>{t.title}</strong><br/><small>{t.description}</small></td><td>{t.priority}</td><td>{t.dueDate||"-"}</td><td><select className="form-select form-select-sm" value={t.status} onChange={async e=>{await taskApi.updateStatus(t.id,e.target.value);load()}}><option>ASSIGNED</option><option>IN_PROGRESS</option><option>COMPLETED</option></select></td><td><button className="btn btn-sm btn-light text-danger" onClick={async()=>{if(confirm("Delete task?")){await taskApi.delete(t.id);load()}}}><i className="bi bi-trash"></i></button></td></tr>)}</tbody></table></div></div></>;
}
